name: If clause for OS

on:
  workflow_dispatch:

jobs:

  ifthen-statement:
    runs-on: macos-latest

    steps:
      - name: condition 1
        if: ${{ runner.os }} == 'Windows'
        run: echo "The operating system on the runner is $env:RUNNER_OS."
      - name: condition 2
        if: runner.os != 'Windows'
        run: echo "The operating system on the runner is not Windows, it's $RUNNER_OS."


